# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    container_name: mysql-test
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: stav
    ports:
      - 3306:3306